### ISSUE TITLE
Duplicate comment entries in CommentMap

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#856]
**Describe the bug**
Disclaimer: I'm not sure if that's a bug, but this behavior is surprising.

**Input code**
```ts
// test.ts

class Foo {
    static _extensions: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        [key: string]: (module: Module, filename: string) => any;
    } = Object.create(null);
}
```

After parsing module using default `Syntax::TypeScript` and taking the comments I'm printing them all:
```rust
  fn parse_ignore_directives(
    &self,
    leading: &CommentMap,
  ) -> Vec<IgnoreDirective> {
    let mut ignore_directives = vec![];

    leading.iter().for_each(|ref_multi| {
      eprintln!("ref multi {:#?} {:#?}", ref_multi.key(), ref_multi.value());
      for comment in ref_multi.value() {
        eprintln!("comment! {:#?}", comment);
        if let Some(ignore) = self.parse_ignore_comment(comment) {
          ignore_directives.push(ignore);
        }
      }
    });

    ignore_directives
  }

```

Here's the output:
```
ref multi BytePos(
    117,
) [
    Comment {
        kind: Line,
        span: Span {
            lo: BytePos(
                46,
            ),
            hi: BytePos(
                108,
            ),
            ctxt: #0,
        },
        text: " eslint-disable-next-line @typescript-eslint/no-explicit-any",
    },
    Comment {
        kind: Line,
        span: Span {
            lo: BytePos(
                46,
            ),
            hi: BytePos(
                108,
            ),
            ctxt: #0,
        },
        text: " eslint-disable-next-line @typescript-eslint/no-explicit-any",
    },
]
comment! Comment {
    kind: Line,
    span: Span {
        lo: BytePos(
            46,
        ),
        hi: BytePos(
            108,
        ),
        ctxt: #0,
    },
    text: " eslint-disable-next-line @typescript-eslint/no-explicit-any",
}
comment! Comment {
    kind: Line,
    span: Span {
        lo: BytePos(
            46,
        ),
        hi: BytePos(
            108,
        ),
        ctxt: #0,
    },
    text: " eslint-disable-next-line @typescript-eslint/no-explicit-any",
}
```

The comment is duplicated in resulting `CommentMap`. As stated before I'm not sure if that's desired behavior - if so, no problem, it's trivial to handle such situation, but again, a bit surprising to see exactly the same entry twice.

**Additional context**
Full source code of parser is available here:
https://github.com/denoland/deno_lint/blob/2a7ff9f936ddf55f97dec33cfe167c1a940c68a6/src/linter.rs#L127-L145

**Comment by kdy1** [comment]
Fixed and published a new version

**Comment by bartlomieju** [comment]
Thanks @kdy1!

**Comment by bartlomieju** [comment]
@kdy1 unfortunately I'm seeing the same problem using `swc_ecma_parser 0.26.0`

Following code snippets produce duplicate entries in leading comments:
```ts
type ConsoleExamineFunc = (
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  csl: any,
  out: StringBuffer,
  err?: StringBuffer,
  both?: StringBuffer
) => void;
```

(I believe this one is used as a test case, but I'm still getting duplicates :( )
```ts
static _extensions: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    [key: string]: (module: Module, filename: string) => any;
  } = Object.create(null);
```

**Only the first comment is duplicated** (I guess it has to do something with `(` or `{` token preceding comments)
```ts
type RequireWrapper = (
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  exports: any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  require: any,
  module: Module,
  __filename: string,
  __dirname: string
) => void;
```

**Comment by kdy1** [comment]
@bartlomieju I added some tests, but I failed to reproduce it.
Does it run in parallel? If it is, it's related to #872.

**Comment by bartlomieju** [comment]
@kdy1 I also tried adding tests but they indeed pass.

> Does it run in parallel? If it is, it may be related to #872.

That's correct, linter is run on multiple threads. I tried upgrading to `swc_common 0.6.1` and `swc_ecma_parser 0.26.1` but the problem persists. I'll try to isolate it better and get back to you.

**Comment by kdy1** [comment]
@bartlomieju Can you share the steps to reproduce?
Building whole deno is an acceptable solution to me, because I need to fix it anyway as spack sometimes aborts due to the concurrency issue

**Comment by bartlomieju** [comment]
@kdy1 the easiest way to reproduce:
- checkout `deno` branch from this PR: https://github.com/denoland/deno/pull/6592 (uses relative path to `deno_lint` crate!)
- checkout `deno_lint` branch from this PR: https://github.com/denoland/deno_lint/pull/207
- in `deno` repo run: `cargo test lint`

You should see following errors:
```
test deno_lint_glob ... ok
(ban-unused-ignore) Ignore for code "no-explicit-any" was not used.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/test_util/../cli/tests/unit/console_test.ts:825:2

(ban-unused-ignore) Ignore for code "no-explicit-any" was not used.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/test_util/../std/node/module.ts:104:4

(ban-unused-ignore) Ignore for code "no-explicit-any" was not used.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/test_util/../std/node/module.ts:1048:2

Found 3 problems
test std_lint ... FAILED
```

Keep in mind that not applying `deno_lint` PR described above makes issue go away because I explicitly deduplicate found comments.

**Comment by kdy1** [comment]
I tried it, but I got compilation failure

```

 Compiling deno_typescript v0.48.2 (/Users/kdy1/projects/deno/deno_typescript)
error: couldn't read deno_typescript/typescript/lib/typescript.js: No such file or directory (os error 2)
  --> deno_typescript/lib.rs:27:32
   |
27 | static TYPESCRIPT_CODE: &str = include_str!("typescript/lib/typescript.js");
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read deno_typescript/typescript/lib/typescript.js: No such file or directory (os error 2)
  --> deno_typescript/lib.rs:27:32
   |
27 | static TYPESCRIPT_CODE: &str = include_str!("typescript/lib/typescript.js");
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read deno_typescript/typescript/package.json: No such file or directory (os error 2)
  --> deno_typescript/lib.rs:32:14
   |
32 |   let data = include_str!("typescript/package.json");
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read deno_typescript/typescript/package.json: No such file or directory (os error 2)
  --> deno_typescript/lib.rs:32:14
   |
32 |   let data = include_str!("typescript/package.json");
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)


```

I tried `npm i` in all of deno / dlint / `deno/deno_typscript`

**Comment by bartlomieju** [comment]
@kdy1 sorry, I forgot to mention you should check out git submodules: ` git submodule update --init --recursive`

**Comment by kdy1** [comment]
It turns out that it's not related to concurrency issue.
Hence it's a bug of lexer or parser.

I'll investigate further.

**Comment by kdy1** [comment]
I found the root cause. It's related to backtracing. I'll fix it soon.
