### ISSUE TITLE
Tsconfig JSX = "preserve" Support

### ISSUE THREAD

**Issue by geospatialweb** [swc-project/swc#9929]
### Describe the feature

As I understand it, SWC only supports the React options available in tsconfig JSX - which therefore excludes Vue JSX that I'm using.  Thus no support for SWC tsconfig `emitDecoratorMetadata = true` which is not supported by Vite esbuild - hence my desire to switch to SWC (plus Rust performance gains) but I cannot because I am not using React. Any thoughts or possibilities?

**Comment by XiNiHa** [comment]
This also blocks the use of SWC (and maybe Rspack families?) in building Solid libraries since Solid libraries need to ship files with JSX preserved.

**Comment by chenjiahan** [comment]
@kdy1 Could you release "@swc/types" for https://github.com/swc-project/swc/pull/10691? Thank you!

**Comment by NunoCruzSW** [comment]
I agree—I’m very disappointed that neither the SWC team nor the SolidJS team seems to be addressing this. I’m stuck on Webpack, and while I tried Vite, it was difficult to integrate with my codebase. Right now I don’t feel like I have a solid toolchain to use Solid with SWC or anything that offers similar performance.

**Comment by chenjiahan** [comment]
@NunoCruzSW https://github.com/swc-project/swc/pull/10691 has been merged to the dev branch. When this change is released (probably SWC v2), you will be able to preserve Solid JSX in Rspack or [Rslib](https://github.com/web-infra-dev/rslib).

**Comment by kdy1** [comment]
@magic-akari Do you think we should resolve this issue before v2? I think v2 will take a long time to come out

**Comment by magic-akari** [comment]
Here are a few possible approaches:

1.  Cherry-pick only the commits related to the `preserve` option and merge them into the main branch.
2.  Merge all the JSX-related changes into the main branch (this might be considered if option 1 proves difficult, **although I don't recommend it**).
3.  Consider releasing an alpha version of v2 earlier than planned.

Option 1 may introduce some additional migration overhead.
Both options 2 and 3 represent **breaking changes**. They could be viable **if users don't require other community SWC plugins, or exclusively use their own custom-built SWC plugins**.

**Comment by kdy1** [comment]
I think cherry picking is the way to go

**Comment by NunoCruzSW** [comment]
Looking forward for this. I don't use react and even for react devs trying to move to other jsx libraries it will be a plus

**Comment by luoye-fe** [comment]
It seems that `@swc/types` hasn't been updated yet, the types for `jsc.transform.react` still don't include preserve related types. @kdy1

**Comment by NunoCruzSW** [comment]
not sure of the documentation needs also to be updated

**Comment by kdy1** [comment]
@luoye-fe Can you send a PR?

@NunoCruzSW Doc need an update, too

**Comment by chenjiahan** [comment]
@kdy1 PRs submitted 😄

- https://github.com/swc-project/swc/pull/11068
- https://github.com/swc-project/website/pull/298

**Comment by kdy1** [comment]
@chenjiahan Thank you!

**Comment by chenjiahan** [comment]
My pleasure! Happy to contribute 😄

**Comment by NunoCruzSW** [comment]
Thanks for doing this.
I was try to use this to use with solidjs, and jest to overcome some slowness with tools used.
It seems not published I think.
can this be used to pipe babel plugin after SWC compiling to jsx?
